name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: HTML5 Validator
      uses: Cyb3r-Jak3/html5validator-action@v0.4
      with:
        # Path of the files to test
        root: .
        # Extra arguments to test with
        # Format for logging output. Valid values: gnu,xml,json,text
        format: text
        # Logging Level. Valid values: DEBUG, INFO, WARNING. Default: WARNING
        log_level: DEBUG, INFO, WARNING
        # Checks css as well
        css: true
        # Flag that increase verbose output only used for troubleshooting the action.
        action_debug: true
